import type { Metadata } from 'next';
import { IBM_Plex_Sans_Arabic } from 'next/font/google';
import '../globals.css';

import i18nConfig from '@/i18nConfig';
import { dir } from 'i18next';
import { ReactNode } from 'react';
import { ThemeProvider } from '@/components/theme-provider';
import TranslationsProvider from '@/components/TranslationsProvider';
import initTranslations from '../i18n';


const IBM_Plex_Sans = IBM_Plex_Sans_Arabic({
	variable: '--font-plex-sans',
	subsets: ['arabic', 'latin'],
	weight: ['400', '500', '600', '700'],
	fallback: ['sans-serif'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export function generateStaticParams() {
	return i18nConfig.locales.map((locale) => ({ locale }));
}

const i18nNamespaces = ['general'];

export default async function RootLayout({ children, params }: { children: ReactNode; params: { locale: string } }) {
	const { locale } = await params;
	const direction = dir(locale);

	const { resources } = await initTranslations(locale, i18nNamespaces);

	return (
		<html lang={locale} dir={direction} suppressHydrationWarning>
			<body className={`${IBM_Plex_Sans.variable} antialiased`}>
				<TranslationsProvider namespaces={i18nNamespaces} locale={locale} resources={resources}>
					<ThemeProvider attribute='class' defaultTheme='system' enableSystem>
						{children}
					</ThemeProvider>
				</TranslationsProvider>
			</body>
		</html>
	);
}
